name: Create GitHub Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Get Tag
        run: echo "REPO_TAG=$(echo "${{ github.ref_name }}" | sed 's/^v//')" >> $GITHUB_ENV
      - name: Generate Changelog
        run: |
          pip install towncrier
          towncrier build --draft
          cat $(ls -t changelog.d/*.fixed | head -n 1)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Build Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine rpm-build debhelper python3-all

      - name: Build WHL
        run: |
          python -m build
          ls dist/

      - name: Upload WHL Artifact
        uses: actions/upload-artifact@v3
        with:
          name: cobbler-tftp-wheel-${{ env.REPO_TAG }}
          path: dist/*.whl

      - name: Build RPM
        run: |
          mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
          python -m build --format wheel
          cp dist/*.whl ~/rpmbuild/SOURCES/
          echo "%define version ${REPO_TAG}" > ~/rpmbuild/.version
          rpmbuild --define "_topdir $(pwd)/../rpmbuild" \
                  --define "version ${REPO_TAG}" \
                  -ba setup.py
          ls ~/rpmbuild/RPMS/noarch/

      - name: Upload RPM Artifact
        uses: actions/upload-artifact@v3
        with:
          name: cobbler-tftp-rpm-${{ env.REPO_TAG }}
          path: ~/rpmbuild/RPMS/noarch/*.rpm

      - name: Build DEB
        run: |
          python -m build
          cp dist/*.whl ..
          dpkg-buildpackage -us -uc -b --changes-option=-y
          ls ../

      - name: Upload DEB Artifact
        uses: actions/upload-artifact@v3
        with:
          name: cobbler-tftp-deb-${{ env.REPO_TAG }}
          path: ../*.deb

      - name: Create Release
        uses: ncipollo/release-action@v1.16.0
        with:
          # Put release artifacts here.
          artifacts: "cobbler-tftp-wheel-${{ env.REPO_TAG }}, cobbler-tftp-rpm-${{ env.REPO_TAG }}, cobbler-tftp-deb-${{ env.REPO_TAG }}"
