name: Lint
on:
  push:
    branches:  [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint_docs:
    name: rstcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Set up Python
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version: 3.13
    - name: Install dependencies
      run:  pip install -U rstcheck doc8 sphinx
    - name: Run rstcheck
      run:  rstcheck -r docs
    - name: Run doc8
      run: doc8 --ignore D001 docs
  python_black:
      name: black formatter
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        - name: Check files using the black formatter
          uses: psf/black@87928e6d6761a4a6d22250e1fee5601b3998086e # stable
          with:
            options: "--check --safe --verbose"
            version: "22.3.0"
  pyright:
      name: pyright
      runs-on: ubuntu-latest
      strategy:
        matrix:
          python-version: ["3.11", "3.12", "3.13"]
      steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[lint_requires,tests_require]
      - name: Analysing the code with pyright
        run: |
          pyright $(git ls-files '*.py')
  isort:
    name: isort
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Set up Python
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version: 3.13
    - uses: isort/isort-action@24d8a7a51d33ca7f36c3f23598dafa33f7071326 # v1.1.1
      with:
        requirementsFiles: "pyproject.toml"

